[tools]
node = "14.21.3"
"npm:workspaced" = "0.1.0"

[tasks."install:dependencies"]
run = "npm install"

[tasks."test:unit"]
run = "npm run test"
depends = ["install:dependencies"]

[tasks."lint:run"]
run = "workspaced lint"

[tasks."codegen:run"]
run = "echo 'No codegen'"
