name: Autorelease

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install mise
        uses: jdx/mise-action@v4.0.0
        with:
          version: 2026.3.9

      - name: Install
        run: mise run install

      - name: Codegen
        run: mise run codegen

      - name: PR if difference
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected after codegen. You should commit them."
            git status
            git diff
            exit 1
          fi

      - name: CI
        run: mise run test

      - name: Release
        run: echo "No release step"

      - name: Artifacts
        uses: actions/upload-artifact@v7.0.0
        with:
          name: coverage-report.tar
          path: coverage.tar